package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.22

import (
	"context"

	"github.com/dsogari/barber-shop/graph/generated"
	"gorm.io/gorm/clause"
)

// CreateShop is the resolver for the createShop field.
func (r *mutationResolver) CreateShop(ctx context.Context, input generated.ShopInput) (*generated.Shop, error) {
	var object generated.Shop
	object.UpdateFrom(input)
	err := CreateObject(&object)
	return &object, err
}

// UpdateShop is the resolver for the updateShop field.
func (r *mutationResolver) UpdateShop(ctx context.Context, id int, input generated.ShopInput) (*generated.Shop, error) {
	var object generated.Shop
	object.ID = id
	object.UpdateFrom(input)
	err := UpdateObject(&object)
	return &object, err
}

// DeleteShop is the resolver for the deleteShop field.
func (r *mutationResolver) DeleteShop(ctx context.Context, id int) (*generated.Shop, error) {
	return DeleteObject[generated.Shop](id)
}

// CreateService is the resolver for the createService field.
func (r *mutationResolver) CreateService(ctx context.Context, input generated.ServiceInput) (*generated.Service, error) {
	var object generated.Service
	object.UpdateFrom(input)
	err := CreateObject(&object)
	return &object, err
}

// UpdateService is the resolver for the updateService field.
func (r *mutationResolver) UpdateService(ctx context.Context, id int, input generated.ServiceInput) (*generated.Service, error) {
	var object generated.Service
	object.ID = id
	object.UpdateFrom(input)
	err := UpdateObject(&object)
	return &object, err
}

// DeleteService is the resolver for the deleteService field.
func (r *mutationResolver) DeleteService(ctx context.Context, id int) (*generated.Service, error) {
	return DeleteObject[generated.Service](id)
}

// CreateClient is the resolver for the createClient field.
func (r *mutationResolver) CreateClient(ctx context.Context, input generated.ClientInput) (*generated.Client, error) {
	var object generated.Client
	object.UpdateFrom(input)
	err := CreateObject(&object)
	return &object, err
}

// UpdateClient is the resolver for the updateClient field.
func (r *mutationResolver) UpdateClient(ctx context.Context, id int, input generated.ClientInput) (*generated.Client, error) {
	var object generated.Client
	object.ID = id
	object.UpdateFrom(input)
	err := UpdateObject(&object)
	return &object, err
}

// DeleteClient is the resolver for the deleteClient field.
func (r *mutationResolver) DeleteClient(ctx context.Context, id int) (*generated.Client, error) {
	return DeleteObject[generated.Client](id)
}

// CreateBarber is the resolver for the createBarber field.
func (r *mutationResolver) CreateBarber(ctx context.Context, input generated.BarberInput) (*generated.Barber, error) {
	var object generated.Barber
	object.UpdateFrom(input)
	err := CreateObject(&object)
	return &object, err
}

// UpdateBarber is the resolver for the updateBarber field.
func (r *mutationResolver) UpdateBarber(ctx context.Context, id int, input generated.BarberInput) (*generated.Barber, error) {
	var object generated.Barber
	object.ID = id
	object.UpdateFrom(input)
	err := UpdateObject(&object)
	return &object, err
}

// DeleteBarber is the resolver for the deleteBarber field.
func (r *mutationResolver) DeleteBarber(ctx context.Context, id int) (*generated.Barber, error) {
	return DeleteObject[generated.Barber](id)
}

// CreateAttendance is the resolver for the createAttendance field.
func (r *mutationResolver) CreateAttendance(ctx context.Context, input generated.AttendanceInput) (*generated.Attendance, error) {
	var object generated.Attendance
	object.UpdateFrom(input)
	err := CreateObject(&object)
	return &object, err
}

// UpdateAttendance is the resolver for the updateAttendance field.
func (r *mutationResolver) UpdateAttendance(ctx context.Context, id int, input generated.AttendanceInput) (*generated.Attendance, error) {
	var object generated.Attendance
	object.ID = id
	object.UpdateFrom(input)
	err := UpdateObject(&object)
	return &object, err
}

// DeleteAttendance is the resolver for the deleteAttendance field.
func (r *mutationResolver) DeleteAttendance(ctx context.Context, id int) (*generated.Attendance, error) {
	return DeleteObject[generated.Attendance](id)
}

// AddAttendanceServices is the resolver for the addAttendanceServices field.
func (r *mutationResolver) AddAttendanceServices(ctx context.Context, id int, serviceIDs []int) (*generated.Attendance, error) {
	var attendance generated.Attendance
	var services []generated.Service
	if err := Db.First(&attendance, id).Error; err != nil {
		return nil, err
	} else if err = Db.Find(&services, serviceIDs).Error; err != nil {
		return nil, err
	} else if err = Db.Model(&attendance).Association("Services").Append(services); err != nil {
		return nil, err
	}
	err := Db.Preload(clause.Associations).First(&attendance).Error
	return &attendance, err
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

type mutationResolver struct{ *Resolver }
