package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.22

import (
	"context"
	"fmt"

	"github.com/dsogari/barber-shop/graph/generated"
	"github.com/dsogari/barber-shop/orm"
)

// CreateShop is the resolver for the createShop field.
func (r *mutationResolver) CreateShop(ctx context.Context, input generated.ShopInput) (*generated.Shop, error) {
	var object generated.Shop
	object.UpdateFrom(input)
	err := orm.Db.Create(&object).Error
	return &object, err
}

// UpdateShop is the resolver for the updateShop field.
func (r *mutationResolver) UpdateShop(ctx context.Context, id int, input generated.ShopInput) (*generated.Shop, error) {
	object := generated.Shop{ID: id}
	object.UpdateFrom(input)
	err := orm.Db.Model(&object).Updates(object).Error
	return &object, err
}

// DeleteShop is the resolver for the deleteShop field.
func (r *mutationResolver) DeleteShop(ctx context.Context, id int) (*generated.Shop, error) {
	var object generated.Shop
	err := orm.Db.Delete(&object, id).Error
	return &object, err
}

// CreateService is the resolver for the createService field.
func (r *mutationResolver) CreateService(ctx context.Context, input generated.ServiceInput) (*generated.Service, error) {
	var object generated.Service
	object.UpdateFrom(input)
	err := orm.Db.Create(&object).Error
	return &object, err
}

// UpdateService is the resolver for the updateService field.
func (r *mutationResolver) UpdateService(ctx context.Context, id int, input generated.ServiceInput) (*generated.Service, error) {
	object := generated.Service{ID: id}
	object.UpdateFrom(input)
	err := orm.Db.Model(&object).Updates(object).Error
	return &object, err
}

// DeleteService is the resolver for the deleteService field.
func (r *mutationResolver) DeleteService(ctx context.Context, id int) (*generated.Service, error) {
	var object generated.Service
	err := orm.Db.Delete(&object, id).Error
	return &object, err
}

// CreateClient is the resolver for the createClient field.
func (r *mutationResolver) CreateClient(ctx context.Context, input generated.ClientInput) (*generated.Client, error) {
	var object generated.Client
	object.UpdateFrom(input)
	err := orm.Db.Create(&object).Error
	return &object, err
}

// UpdateClient is the resolver for the updateClient field.
func (r *mutationResolver) UpdateClient(ctx context.Context, id int, input generated.ClientInput) (*generated.Client, error) {
	object := generated.Client{ID: id}
	object.UpdateFrom(input)
	err := orm.Db.Model(&object).Updates(object).Error
	return &object, err
}

// DeleteClient is the resolver for the deleteClient field.
func (r *mutationResolver) DeleteClient(ctx context.Context, id int) (*generated.Client, error) {
	var object generated.Client
	err := orm.Db.Delete(&object, id).Error
	return &object, err
}

// CreateBarber is the resolver for the createBarber field.
func (r *mutationResolver) CreateBarber(ctx context.Context, input generated.BarberInput) (*generated.Barber, error) {
	var object generated.Barber
	object.UpdateFrom(input)
	err := orm.Db.Create(&object).Error
	return &object, err
}

// UpdateBarber is the resolver for the updateBarber field.
func (r *mutationResolver) UpdateBarber(ctx context.Context, id int, input generated.BarberInput) (*generated.Barber, error) {
	object := generated.Barber{ID: id}
	object.UpdateFrom(input)
	err := orm.Db.Model(&object).Updates(object).Error
	return &object, err
}

// DeleteBarber is the resolver for the deleteBarber field.
func (r *mutationResolver) DeleteBarber(ctx context.Context, id int) (*generated.Barber, error) {
	var object generated.Barber
	err := orm.Db.Delete(&object, id).Error
	return &object, err
}

// CreateAttendance is the resolver for the createAttendance field.
func (r *mutationResolver) CreateAttendance(ctx context.Context, input generated.AttendanceInput) (*generated.Attendance, error) {
	var object generated.Attendance
	object.UpdateFrom(input)
	err := orm.Db.Create(&object).Error
	return &object, err
}

// UpdateAttendance is the resolver for the updateAttendance field.
func (r *mutationResolver) UpdateAttendance(ctx context.Context, id int, input generated.AttendanceInput) (*generated.Attendance, error) {
	object := generated.Attendance{ID: id}
	object.UpdateFrom(input)
	err := orm.Db.Model(&object).Updates(object).Error
	return &object, err
}

// DeleteAttendance is the resolver for the deleteAttendance field.
func (r *mutationResolver) DeleteAttendance(ctx context.Context, id int) (*generated.Attendance, error) {
	var object generated.Attendance
	err := orm.Db.Delete(&object, id).Error
	return &object, err
}

// AddAttendanceServices is the resolver for the addAttendanceServices field.
func (r *mutationResolver) AddAttendanceServices(ctx context.Context, id int, serviceIDs []int) (*generated.Attendance, error) {
	panic(fmt.Errorf("not implemented: AddAttendanceServices - addAttendanceServices"))
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

type mutationResolver struct{ *Resolver }
