package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.22

import (
	"context"

	"github.com/dsogari/barber-shop/graph/generated"
	"gorm.io/gorm/clause"
)

// ListShop is the resolver for the listShop field.
func (r *queryResolver) ListShop(ctx context.Context) ([]*generated.Shop, error) {
	return ListObjects[generated.Shop]()
}

// GetShop is the resolver for the getShop field.
func (r *queryResolver) GetShop(ctx context.Context, id int) (*generated.Shop, error) {
	return GetObject[generated.Shop](id)
}

// ListService is the resolver for the listService field.
func (r *queryResolver) ListService(ctx context.Context) ([]*generated.Service, error) {
	return ListObjects[generated.Service]()
}

// GetService is the resolver for the getService field.
func (r *queryResolver) GetService(ctx context.Context, id int) (*generated.Service, error) {
	return GetObject[generated.Service](id)
}

// ListClient is the resolver for the listClient field.
func (r *queryResolver) ListClient(ctx context.Context) ([]*generated.Client, error) {
	return ListObjects[generated.Client]()
}

// GetClient is the resolver for the getClient field.
func (r *queryResolver) GetClient(ctx context.Context, id int) (*generated.Client, error) {
	return GetObject[generated.Client](id)
}

// ListBarber is the resolver for the listBarber field.
func (r *queryResolver) ListBarber(ctx context.Context) ([]*generated.Barber, error) {
	return ListObjects[generated.Barber]()
}

// GetBarber is the resolver for the getBarber field.
func (r *queryResolver) GetBarber(ctx context.Context, id int) (*generated.Barber, error) {
	return GetObject[generated.Barber](id)
}

// ListAttendance is the resolver for the listAttendance field.
func (r *queryResolver) ListAttendance(ctx context.Context) ([]*generated.Attendance, error) {
	return ListObjects[generated.Attendance]()
}

// GetAttendance is the resolver for the getAttendance field.
func (r *queryResolver) GetAttendance(ctx context.Context, id int) (*generated.Attendance, error) {
	return GetObject[generated.Attendance](id)
}

// SearchAttendance is the resolver for the searchAttendance field.
func (r *queryResolver) SearchAttendance(ctx context.Context, input generated.AttendanceSearchInput) ([]*generated.Attendance, error) {
	var objects []*generated.Attendance
	err := Db.Preload(clause.Associations).Find(&objects, "attended_at BETWEEN ? AND ?"+
		getIntArray("shop_id", input.ShopIDs)+
		getIntArray("barber_id", input.BarberIDs)+
		getIntArray("client_id", input.ClientIDs), input.Begin, input.End).Error
	return objects, err
}

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
