// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Attendance struct {
	ID         int        `json:"id"`
	CreatedAt  int        `json:"createdAt"`
	UpdatedAt  int        `json:"updatedAt"`
	DeletedAt  *int       `json:"deletedAt"`
	ShopID     int        `json:"shopID"`
	BarberID   int        `json:"barberID"`
	ClientID   int        `json:"clientID"`
	Shop       *Shop      `json:"shop"`
	Barber     *Barber    `json:"barber"`
	Client     *Client    `json:"client"`
	AttendedAt int        `json:"attendedAt" gorm:"autoCreateTime"`
	Notes      *string    `json:"notes"`
	Services   []*Service `json:"services" gorm:"many2many:attendance_services;"`
}

type AttendanceInput struct {
	ShopID     *int    `json:"shopID"`
	BarberID   *int    `json:"barberID"`
	ClientID   *int    `json:"clientID"`
	AttendedAt *int    `json:"attendedAt"`
	Notes      *string `json:"notes"`
}

type AttendanceMutation struct {
	CreateAttendance      *Attendance `json:"createAttendance"`
	UpdateAttendance      *Attendance `json:"updateAttendance"`
	DeleteAttendance      *Attendance `json:"deleteAttendance"`
	AddAttendanceServices *Attendance `json:"addAttendanceServices"`
}

type AttendanceQuery struct {
	ListAttendance   []*Attendance `json:"listAttendance"`
	GetAttendance    *Attendance   `json:"getAttendance"`
	SearchAttendance []*Attendance `json:"searchAttendance"`
}

type AttendanceSearchInput struct {
	ShopIDs   []int `json:"shopIDs"`
	BarberIDs []int `json:"barberIDs"`
	ClientIDs []int `json:"clientIDs"`
	Begin     *int  `json:"begin"`
	End       *int  `json:"end"`
}

type Barber struct {
	ID          int     `json:"id"`
	CreatedAt   int     `json:"createdAt"`
	UpdatedAt   int     `json:"updatedAt"`
	DeletedAt   *int    `json:"deletedAt"`
	Name        string  `json:"name"`
	PhoneNumber *string `json:"phoneNumber"`
	Notes       *string `json:"notes"`
}

type BarberInput struct {
	Name        *string `json:"name"`
	PhoneNumber *string `json:"phoneNumber"`
	Notes       *string `json:"notes"`
}

type BarberMutation struct {
	CreateBarber *Barber `json:"createBarber"`
	UpdateBarber *Barber `json:"updateBarber"`
	DeleteBarber *Barber `json:"deleteBarber"`
}

type BarberQuery struct {
	ListBarber []*Barber `json:"listBarber"`
	GetBarber  *Barber   `json:"getBarber"`
}

type Client struct {
	ID          int     `json:"id"`
	CreatedAt   int     `json:"createdAt"`
	UpdatedAt   int     `json:"updatedAt"`
	DeletedAt   *int    `json:"deletedAt"`
	Name        string  `json:"name"`
	PhoneNumber *string `json:"phoneNumber"`
	Notes       *string `json:"notes"`
}

type ClientInput struct {
	Name        *string `json:"name"`
	PhoneNumber *string `json:"phoneNumber"`
	Notes       *string `json:"notes"`
}

type ClientMutation struct {
	CreateClient *Client `json:"createClient"`
	UpdateClient *Client `json:"updateClient"`
	DeleteClient *Client `json:"deleteClient"`
}

type ClientQuery struct {
	ListClient []*Client `json:"listClient"`
	GetClient  *Client   `json:"getClient"`
}

type Service struct {
	ID          int           `json:"id"`
	CreatedAt   int           `json:"createdAt"`
	UpdatedAt   int           `json:"updatedAt"`
	DeletedAt   *int          `json:"deletedAt"`
	Name        string        `json:"name"`
	Cost        int           `json:"cost" gorm:"default:30"`
	Notes       *string       `json:"notes"`
	Attendances []*Attendance `json:"-" gorm:"many2many:attendance_services;"`
}

type ServiceInput struct {
	Name  *string `json:"name"`
	Cost  *int    `json:"cost"`
	Notes *string `json:"notes"`
}

type ServiceMutation struct {
	CreateService *Service `json:"createService"`
	UpdateService *Service `json:"updateService"`
	DeleteService *Service `json:"deleteService"`
}

type ServiceQuery struct {
	ListService []*Service `json:"listService"`
	GetService  *Service   `json:"getService"`
}

type Shop struct {
	ID          int     `json:"id"`
	CreatedAt   int     `json:"createdAt"`
	UpdatedAt   int     `json:"updatedAt"`
	DeletedAt   *int    `json:"deletedAt"`
	Address     string  `json:"address"`
	PhoneNumber *string `json:"phoneNumber"`
	Notes       *string `json:"notes"`
}

type ShopInput struct {
	Address     *string `json:"address"`
	PhoneNumber *string `json:"phoneNumber"`
	Notes       *string `json:"notes"`
}

type ShopMutation struct {
	CreateShop *Shop `json:"createShop"`
	UpdateShop *Shop `json:"updateShop"`
	DeleteShop *Shop `json:"deleteShop"`
}

type ShopQuery struct {
	ListShop []*Shop `json:"listShop"`
	GetShop  *Shop   `json:"getShop"`
}
